### ISSUE TITLE
 auto-upload

### ISSUE THREAD

**Issue by JohnHasthorpe** [Esri/QuickCapture#18]
Add auto-upload functionality. This should happen as soon as the device goes online.

Requested by Gareth Walters (esri Aus)

> 

> 

> Enhancements: The only draw back in it currently is they would like the app to auto upload. Store locally when offline and when online just send the data straight away.

**Comment by JohnHasthorpe** [comment]
Raised by Minnesota Power. Users are not always aware of the fact that the must upload their features. Auto upload would provide a solution to this issue, together with making it clearer in the app that the button must be pressed.

**Comment by spatialdude** [comment]
Implemented auto upload -
* Options in settings to enable and set interval
* Upload will trigger automatically every interval when device is online

**Comment by JohnHasthorpe** [comment]
Have verified that the auto-upload functionality is working.
- Varying the interval works
- Upload automatically starts when the project is in focus and the timer runs out
- Upload will not start unless the device is online
- Points, lines and polygons (and attachments) uploaded

Version 1.0.59 Tested on the following:
- Surface Book Pro - Windows 10 (Desktop and UWP)
- IPhone 7 Plus - 11.4.1
- Nexus 6P - Android 8
