### ISSUE TITLE
Unable to switch user without closing app

### ISSUE THREAD

**Issue by JohnHasthorpe** [Esri/QuickCapture#19]
If you click the **switch user** button and sign in with another login, the app hangs on the sign in page.
It is possible to go back and exit the sign in page, but then the sign in as other user button is disabled.
The only option is to close the app and sign in again.

Video: https://www.youtube.com/watch?v=wFxd2XRoEHI

Tested on the following devices:
iPhone 7 Plus iOS 11.0.3 (JH)
iPhone X iOS 11.2.6

Also affects Windows

**Comment by spatialdude** [comment]
Previous user is now signed out before signing in as a different user
Pressing and hold on "Sign in a different user" will sign out the current user and return the app to the unsigned in state.

**Comment by JohnHasthorpe** [comment]
Verified that both methods mentioned in https://github.com/Esri/QuickCapture/issues/19#issuecomment-463882445 are working now (press and hold and sign in as a different user)

Build 1.0.60 Verified on the following devices:
- iPhone 7 Plus iOS 12.0.1 (JH)
- Surface Book - Windows 10
- Blackview BV6000 Android 6.0

Closing
