### ISSUE TITLE
Check for invalid geometry before submission

### ISSUE THREAD

**Issue by JohnHasthorpe** [Esri/QuickCapture#30]
Don't let user submit a line or polyline feature that has less than 2 points. This situation may arise if the user accidentally double taps, or starts collecting a line/polyline in error.

At the moment the user can submit a feature with invalid geometry, and then on upload the app will hang. This results in the loss of all yet to be uploaded data. 

We just need to catch the error on collection and let them recapture the geometry if required:

Error:
_'Warning - Invalid Geometry (< 2 points). 
Please recapture the the feature.'_
```

AppStudio error:

qml: Features added: {
  "addResults": [
    {
      "error": {
        "code": 1000,
        "description": "24117: The LineString input is not valid because it does not have enough distinct points. A LineString must have at least two distinct points."
      },
      "globalId": "4632E2AC-0811-4697-8677-0D8A46B7BA41",
      "objectId": null,
      "success": false
    }
  ]
}
```

**Comment by IsmaelInRedlands** [comment]
Including a screenshot of a polyline captured by a user in Canada. Note that one of the vertices of the line as 0,0 coordinates.  

![untitled](https://user-images.githubusercontent.com/5918689/52821760-a4b99780-3064-11e9-9eff-d8ad021bc9a5.png)
