### ISSUE TITLE
Register QuickCapture in Portal for ArcGIS

### ISSUE THREAD

**Issue by IsmaelInRedlands** [Esri/QuickCapture#34]
Best contact  to register QuickCapture in the next  version of Portal for ArcGIS is Derek Weatherbe in Esri.
I think we still may be on time for 10.6.1 but it is going to be closed  very, very soon.
@JohnHasthorpe

**Comment by JohnHasthorpe** [comment]
This has been actioned and will kick on from 10.7 portal.
QuickCapature will be the client ID.

**Comment by mgg-beca** [comment]
Hi, if we have manually registered QuickCapture with out 10.6.1 portal, what will we have to do when we upgrade to 10.7? Thanks.

**Comment by JohnHasthorpe** [comment]
@mgg-beca - We have added the apps clientid to Portal 10.7.
So no action required when you upgrade.

**Comment by mgg-beca** [comment]
> @mgg-beca - We have added the app's clientid to Portal 10.7.
> So no action required when you upgrade.

Do I need to delete the existing registered app item?
