### ISSUE TITLE
Add support for keyboard events to support bluetooth buttons

### ISSUE THREAD

**Issue by JohnHasthorpe** [Esri/QuickCapture#38]
Pest control company wanted to use a bluetooth button called Flic. For us to support such devices and use them to start and end feature capture etc, we need to listen to keyboard events (letters) and allow users to map them to a quickcapture buttons.

![threeflics](https://user-images.githubusercontent.com/24929507/40633551-b2a6c66e-6333-11e8-9d45-a476f4fd39d2.png)

**Comment by JohnHasthorpe** [comment]
+1 Oil and gas user

**Comment by spatialdude** [comment]
Introduced support for keyboard shortcuts to buttons.

Configuration is via the **key=*keycode*** option which can be added to a template's description.

***keycode*** is the numeric or hexdecimal keycode of the the key to associate with the button.

e.g. To associate the ```A``` key to a button
```// key=65``` 
or in hexdecimal
```// key=0x41``` 

For testing purposes - 

* Key codes can be found by going into the Settings page and then press and hold on the title bar to reveal a key information panel at the bottom of the page. Click on the key information then press keys to show their respective key code.

![image](https://user-images.githubusercontent.com/7235583/45935786-49720480-bff2-11e8-8e05-006f6f173758.png)

* Press and hold on the data capture page title to show buttons that have an associated key

![image](https://user-images.githubusercontent.com/7235583/45935791-61e21f00-bff2-11e8-89bb-d5e37990e6f7.png)

**Comment by JohnHasthorpe** [comment]
Initial testing looks good. 
- Keyboard key listener is working and picks up connect keyboards (physical and Bluetooth)
- Template key-value pairs are working
- Button key indicator text is appearing (when press and hold applied)

Inputs tested
- Logitech keyboard (Bluetooth) works on Windows/UWP and Android (but not iOS)
- Virtual Box joystick (Bluetooth) works on Android and only the joystick (up, down. left and right) generated key events

More testing required......

**Comment by JohnHasthorpe** [comment]
@spatialdude - The iOS keyboard is not working. Crossreferencing the related HawkView commit:

> Added hidden text input to capture key events

https://github.com/ArcGIS/duoculi/commit/f67d823efdb706528c5b31c43de92246f041770c

**Comment by JohnHasthorpe** [comment]
@spatialdude  - It looks like this functionality is only working for point layers, not lines or polygons. Key labels don't appear and buttons are not firing.
