### ISSUE TITLE
Null geometries still possible for lines and polygons

### ISSUE THREAD

**Issue by JohnHasthorpe** [Esri/QuickCapture#43]
If you are collecting multiple line geometries at the same time (in the same group - exclusive = false) it is still possible to capture null geometries. This causes the same submission hanging error that was fixed in the following issue: https://github.com/ArcGIS/QuickCapture/issues/30

We fixed this for situations when collecting one lines/polygons at a time, but not for situations when we have multiple lines/polygons being collected simultaniously.

![fbed001b-d3a3-4f44-bbdf-585ff5e2ad2a](https://user-images.githubusercontent.com/24929507/42197318-12b95256-7e37-11e8-987d-04b1f4fef2a6.GIF)

```
ArcGIS.AppFramework.Network: NetworkNotifier: con:  66

qml: Features added: {
  "addResults": [
    {
      "error": {
        "code": 1000,
        "description": "24117: The LineString input is not valid because it does not have enough distinct points. A LineString must have at least two distinct points."
      },
      "globalId": "93E23D8C-28CD-49A6-AEF0-6854A3C100D8",
      "objectId": nu
ll,
      "success": false,
      "uniqueId": null
    }
  ]
}
```

Take a look at the Line Capture project authored by @spatialdude

**Comment by JohnHasthorpe** [comment]
This issue is the cause of #69. Here the user collected one feature type in a group then started and rapidly stopped a second. The second feature contained the null geometry. It looks like the null geometry check is only being applied to the first feature captured only.

**Comment by IsmaelInRedlands** [comment]
Affecting Maryland.

**Comment by spatialdude** [comment]
* Fixed issue where duplicate sequential vertices were not being filtered out
* Filter out 0,0 vertices in lines and polygons
* Submit undefined (null) geometry if there are insufficient points for a line or polygon

**Comment by JohnHasthorpe** [comment]
Initial testing looks good and initial issue resolved.
We will do some more field testing before closing this one off.

**Comment by JohnHasthorpe** [comment]
Build 1.0.60 Verified
Closing as done.
