### ISSUE TITLE
Support for high accuracy GNSS receivers

### ISSUE THREAD

**Issue by spatialdude** [Esri/QuickCapture#6]
Add support for high accuracy receivers

**Comment by JohnHasthorpe** [comment]
Raised by Minnesota power - they were experiencing delays of about 2-3 seconds when capturing their location when flying a helicopter. An external GPS receiver could reduce the lag in captured location.

**Comment by JohnHasthorpe** [comment]
+1 for connecting to the helicopters GPS -  Hancock Forest Management New Zealand
