### ISSUE TITLE
Feature Service

### ISSUE THREAD

**Issue by TurkeyMan66** [Esri/QuickCapture#75]
Are you able to use a feature service hosted on your own Arcgis Server for this application? If so, how would you go about using it? I have only seen this use with feature layers hosted on AGOL. Thanks.

**Comment by JohnHasthorpe** [comment]
Please see the wiki for steps of how to configure the app with your portal: https://github.com/Esri/QuickCapture/wiki/6.-Using-QuickCapture-with-ArcGIS-Enterprise

**Comment by JohnHasthorpe** [comment]
Can you confirm that the feature service was secured and you saved the credentials in the AGOL  item?
Also, what version of Server are you using?

Thanks
John

**Comment by TurkeyMan66** [comment]
Hi John, I tried to secure the feature service and add it as an item to AGOL. However, we received a token error. We generally do not use secured services but we do use a reverse proxy. Is it possible to use a public feature service? Thank you for the help.

**Comment by TurkeyMan66** [comment]
Hi John,
Thanks for following up. This issue has brought another problem to the surface. I am unable to create a secured service. I receive a "Token Generation Error" through AGOL. So, I have been working with ESRI tech support on that issue. After weeks of troubleshooting with tech support, we are still unable to successfully create a secured service. So, I have not been able to test the appropriate workflow. I will do my best to confirm the workflow you have suggested as soon as we figure out the underlying issue. 
Thanks again.
