### ISSUE TITLE
Custom symbols are not displaying in Quickcapture buttons (Portal)

### ISSUE THREAD

**Issue by mgg-beca** [Esri/QuickCapture#76]
Hi there,  we have Quickcapture registered with our 10.6.1 Portal.  We have created some services with custom image symbols, and they are not showing up on the QC buttons.  I have tried hosting the images in portal as well as direct linking to external websites.  This has been tested on both iOS and Android.

**Comment by JohnHasthorpe** [comment]
Hi @mgg-beca 
This is an issue with the app - I'll convert this issue into a bug.
