### ISSUE TITLE
rowSpacing and columnSpacing properties don't work

### ISSUE THREAD

**Issue by NateJohnsonCNLM** [Esri/QuickCapture#78]
I'm having trouble changing the rowspacing as detailed in section 3 of the QuickCapture documentation.  I've varied the number of pixels from 7 to 70 to 700 and beyond without any change on the quickCapture collection screen. I'm able to change the other parameters- e.g. number of columns without issue. Here's a screen grab from arc online:

![capture](https://user-images.githubusercontent.com/47615766/52753063-1da7e900-2faa-11e9-8e8d-5804277a402c.GIF)

**Comment by JohnHasthorpe** [comment]
This looks to be a bug with both `rowSpacing` and `columnSpacing`.
Applying either to a survey is having no effect:

Example:
// rowSpacing=1000, columnSpacing=1000
